# Background and foreground colors
background = #fdf6ee
foreground = #22211d

# Standard colors
palette = 0=#7a6550
palette = 1=#df2b0d
palette = 2=#29472a
palette = 3=#8a6c3e
palette = 4=#5e8e28
palette = 5=#28473f
palette = 6=#3d6b52
palette = 7=#24201d

# Bright colors
palette = 8=#a09080
palette = 9=#e03c20
palette = 10=#1b2e1c
palette = 11=#6b5237
palette = 12=#496c1e
palette = 13=#28463c
palette = 14=#4a6b4d
palette = 15=#22211d
