$color = rgba(249, 239, 225, 1)
$inner_color = rgba(249, 239, 225, 0.66)
$outer_color = rgba(40, 71, 63, 1)
$font_color = rgba(34, 33, 29, 1)
$placeholder_color = rgba(34, 33, 29, 0.7)
$check_color = rgba(106, 130, 94, 1)
