background            #fdf6ee
foreground            #22211d

# black
color0  #7a6550
color8  #a09080

# red
color1  #df2b0d
color9  #e03c20

# green
color2  #29472a
color10 #1b2e1c

# yellow
color3  #8a6c3e
color11 #6b5237

# blue
color4  #5e8e28
color12 #496c1e

# magenta
color5  #28473f
color13 #28463c

#cyan
color6  #3d6b52
color14 #4a6b4d

#white
color7  #24201d
color15 #22211d


